name: mustache_recase
description: A mustache package extension for handling case conversions through e.g. {{#constant_case}} {{varName}} recased {{#constant_case}}
publish_to: 'none'

version: 2.1.0
homepage: https://gitlab.com/Rodsevich/mustache_recase/
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mustache_template:
    git: https://github.com/chainchelliah/mustache.git
  recase: ^4.0.0

dev_dependencies:
  test: ^1.17.5
