name: mustache_recase
description: A mustache package extension for handling case conversions through e.g. {{#constant_case}} {{varName}} recased {{#constant_case}}
version: 2.0.3
homepage: https://gitlab.com/Rodsevich/mustache_recase/

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  mustache_template: ^1.0.0
  recase: ^3.0.0

dev_dependencies:
  test: ">=0.12.0 <1.4.0"
