name: mustache_recase description: A mustache package extension for handling case conversions through e.g. {{#constant_case}} {{varName}} recased {{#constant_case}} 
version: 1.0.3
homepage: https://gitlab.com/Rodsevich/mustache_recase/
author: Rodsevich <nicorodsevich@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  mustache: '>=1.0.0 <2.0.0'
  recase: ^1.0.0
  generator_plus: ^0.0.0

dev_dependencies:
  test: ^0.12.0
